name: Validate pull request

on:
  pull_request:
    branches: master

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run unit tests
        run: ./unit-tests.sh
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3.3.1
        with:
          buildx-version: latest
      - name: Run integration tests
        run: ./integration-tests.sh
      - name: Run HELM chart tests
        run: ./helm/tests.sh
      - name: Run Buildx
        env:
          PLATFORMS: "linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le"
        run: ./build.sh -t boky/postfix

